import React, { useEffect, useState } from "react";
import CollectionCard from "./components/CollectionCard";
import Link from "next/link";
import { RotatingLines } from "react-loader-spinner";
import Head from "next/head";
const Collections = () => {
  const [collections, setCollections] = useState(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const getCollections = async () => {
      try {
        const response = await fetch(
          "https://neonflake-server.onrender.com/api/thumbnails"
        );
        const data = await response.json();
        setCollections(data?.data);
        setIsLoading(false); // Set loading to false once data is fetched
      } catch (error) {
        console.error("Error fetching collections:", error);
        setIsLoading(false);
      }
    };
    getCollections();
  }, []);

  if (isLoading) {
    return (
      <>
        <Head>
          <title>Collections</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="flex w-full h-screen justify-center items-center">
          <RotatingLines
            strokeColor="grey"
            strokeWidth="5"
            animationDuration="0.4"
            width="100"
            visible={true}
          />
        </div>
      </>
    );
  }

  return (
    <>
      <Head>
        <title>Collections</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-screen font-monstreat p-10">
        <div className="w-full h-10 flex justify-center items-center">
          <Link href={"/"}>
            <button className="border-[1px] absolute lg:top-6 top-8 left-5 lg:p-2 p-1 bg-[#080202] text-white rounded-md shadow-md lg:text-[18px] text-[14px]">
              Go back
            </button>
          </Link>
          <h1 className="lg:text-[50px] text-[30px] font-[600] lg:font-[800] mb-5  tracking-widest">
            Collections
          </h1>
        </div>
        {collections && collections.length > 0 ? (
          <div className="w-full h-fit flex flex-wrap lg:py-5 justify-center items-start">
            {collections.map((collectionInfo) => (
              <CollectionCard key={collectionInfo.id} info={collectionInfo} />
            ))}
          </div>
        ) : (
          <div className="w-full h-full flex justify-center items-center flex-col">
            <p className="text-center text-gray-600 lg:text-[30px] text-[18px]">
              No collections available.
            </p>
            <Link href={"/"}>
              <button className="border-[1px]  p-2 bg-[#080202] text-white rounded-md shadow-md lg:text-[18px] text-[14px] mt-4">
                Start Uploading
              </button>
            </Link>
          </div>
        )}
      </div>
    </>
  );
};

export default Collections;
