import Head from "next/head";
import From from "./components/From";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="w-full h-screen flex lg:justify-normal justify-center">
          <div className="hidden lg:block w-1/2 bg-[#080202] text-white text-[50px] font-[800] p-24 overflow-scroll">
            <p>Unleash Creativity</p>
            Host Your Images and Videos for Free
            <p>on Cloudinary's Seamless Platform.</p>
            <Link href={"/collections"}>
              <button className="w-full p-4 rounded-lg relative top-28 bg-white text-black text-[30px] font-[500]">
                Browse Collection
              </button>
            </Link>
          </div>
          <div className="lg:w-1/2 w-5/6 flex flex-col justify-center items-center">
            <h1 className="lg:text-[30px] text-[23px] font-[600] lg:font-[800] mb-5 font-monstreat">
              Get Started
            </h1>
            <From />
          </div>
        </div>

        <Link
          className="w-full lg:hidden  flex justify-center items-center"
          href={"/collections"}
        >
          <button className=" w-3/5 border-[1px] p-2 relative bottom-10 rounded-lg  text-white bg-black text-[25px] font-[500]">
            Browse Collection
          </button>
        </Link>
      </main>
    </>
  );
}
