import React from "react";
import { useRouter } from "next/router";
import Link from "next/link";
import Head from "next/head";
const View = () => {
  const router = useRouter();
  const { title, videoURL } = router.query;

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Link href={"/collections"}>
          <button className="border-[1px] absolute top-5 left-5 lg:p-2 p-1 bg-[#080202] text-white rounded-md shadow-md lg:text-[18px] text-[14px]">
            Go back
          </button>
        </Link>
        <iframe
          className="w-full h-screen"
          src={videoURL}
          frameborder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
          allowfullscreen
        ></iframe>
      </div>
    </>
  );
};

export default View;
